coverage:
  precision: 2
  round: down
  range: 70...100

  

  status:
    # Learn more at https://docs.codecov.io/docs/commit-status
    project:
      default:
        threshold: 1% # allow this much decrease on project
      app:
        target: 70%
        flags:
          - app
      modules:
        target: 70%
        flags:
          - modules
      client:
        flags:
          - client
    changes: false

comment:
  layout: "reach, diff, files"
  behavior: default # update if exists else create new
  require_changes: true

patch:
  default:
    enabled: no
  
codecov:
  token: "de5f77c6-04e5-4572-be53-fec042d85732"
  bot: "codecov-io"
  ci:
    - "travis.org"

