version: 2.1

jobs:     

  install-and-test:
    build:
    docker:
      - image: cimg/node:16.13.2
    
    steps: 
      - checkout
      - run: 
          name: "Install npm modules in musician"
          command: "cd musician; npm install; npm install jest; npm install --save jest-coverage-badges; sudo npm install -g codecov"

      - run: 
          name: "Run the jest tests"
          command: "npm test"
      
      - run:
          name: "Generate badges from coverage-summary.json"
          command: "npm run badges"


workflows:
  Install-and-test:
    jobs:
      - install-and-test